Create ArturMuniz.md
education/PR-Pao-de-Queijo-Request pull request #370
Opened 2022-06-17 04:30 UTC by ArturMuniz

2022-06-17 04:31 UTC, github-education submitted a review, later dismissed
**Oie ArturMuniz,**
**Bem vindo a Campus Party!**


### I have a few items I need you to take care of before I can merge this PR:

* *Por favor reveja seu arquivo markdown, possui alguns erros:* 
	*The attribute time need to be in the format: YYYY-MM-DD HH:MM:SS. For example: 2022-06-15 17:01:10*

Feel free to re-request a review from me and I'll come back and take a look!

2022-06-18 14:49 UTC, juanpflores commented on _messages/ArturMuniz.md
> +
```suggestion
```

2022-06-18 14:50 UTC, juanpflores commented on _messages/ArturMuniz.md
> +---
```suggestion
---
user: ArturMuniz
time: 2022-06-17 01:30
quote: jogar com os amigos minigames, assitir as palestras e participar dos workshops.
---
```

2022-06-18 14:50 UTC, github-education requested changes
**Oie ArturMuniz,**
**Bem vindo a Campus Party!**


### I have a few items I need you to take care of before I can merge this PR:

* *Por favor reveja seu arquivo markdown, possui alguns erros:* 
	*The attribute time need to be in the format: YYYY-MM-DD HH:MM:SS. For example: 2022-06-15 17:01:10*

Feel free to re-request a review from me and I'll come back and take a look!

2022-06-18 14:51 UTC, github-education requested changes
**Oie ArturMuniz,**
**Bem vindo a Campus Party!**


### I have a few items I need you to take care of before I can merge this PR:

* *Por favor reveja seu arquivo markdown, possui alguns erros:* 
	*The attribute time need to be in the format: YYYY-MM-DD HH:MM:SS. For example: 2022-06-15 17:01:10*

Feel free to re-request a review from me and I'll come back and take a look!

2022-06-18 14:53 UTC, juanpflores approved these changes

2022-06-18 14:53 UTC, merged